version: "3"

services:
  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/app
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: MeetAround
    ports:
      - "5432:5432"
